### ISSUE TITLE
Adjust coordinates

### ISSUE THREAD

**Issue by jehrhardt** [open-data-potsdam/schuleinzugsgebiete#7]
The following coordinates are not correct. The shown address and the point on the map are different.
* https://einzugs.schule/schulen/Grundschule+im+Bornstedter+Feld+-+Rote+Kaserne+Ost
* https://einzugs.schule/schulen/Aktive+Schule+Potsdam+Grundschule
* https://einzugs.schule/schulen/Internationale+Grundschule+Potsdam+Primary+School+genehmigte+Ersatzschule

**Comment by hfs** [comment]
The coordinates in [/data/schools.csv](https://github.com/open-data-potsdam/schuleinzugsgebiete/blob/master/data/schools.csv) were fixed in ab8999c. The live site needs to be redeployed.

**Comment by jehrhardt** [comment]
✅
